### ISSUE TITLE
See also Mozilla Common Voice

### ISSUE THREAD

**Issue by nealmcb** [MycroftAI/openstt#7]
[Mozilla Common Voice](https://blog.mozilla.org/internetcitizen/2017/06/19/commonvoice/) ("Raising Our Common Voice For The Web - Internet Citizen") is a blog post on a new initiative that Mozilla launched 2 weeks ago to crowdsource an open source data set of thousands of hours of text read out loud, with lots of languages and accents.

Everyone should go to [Common Voice](https://voice.mozilla.org/) and add some recordings. It should be very beneficial to MycroftAI.

Combining this with Mozilla's open-source TensorFlow implementation of Baidu's DeepSpeech research, and their soon-to-arrive pre-trained models, as noted in #4, will be another big boost. Read more (from last November, though), including Project PipSqueak (offline local speech recognition for e.g. a Raspberry Pi 3) at [The Next Phase for Project Vaani | Connected Devices](https://connected.mozilla.org/2016/11/28/the-next-phase-for-project-vaani/).

How does this fit in with what the Mycroft team is up to?

**Comment by mikehenrty** [comment]
Hi @nealmcb, I'm a maintainer for Common Voice, and I work with Mozilla's DeepSpeech team. I can't speak for MyCroft directly, but you can rest assured that we are collaborating very diligently with the MyCroft team to build open-source speech technology, and empower more people to join this effort. We very much share values around privacy and openness.

**Comment by nealmcb** [comment]
Thanks, @mikehenrty. I'm glad to see that [Deep Speech 0.1.1](https://github.com/mozilla/DeepSpeech/releases) is out now: a pre-trained Deep Speech model for English that works quite well, with support for slightly older CPUs. Lots to play with now :)
